training:
  lr: 0.01
  weight-decay: 0.000001
  bs: 32
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 5

  skip: 4
  frames-per-video: 40 # Equidistant frames
  real-pic: 50
  fake-pic: 50

model:
  image-size: 224    #224
  num-classes: 1
  depth: 4              # number of multi-scale encoding blocks
  sm-dim: 49            # high res dimension
  sm-patch-size: 7      # high res patch size
  sm-enc-depth: 3        # high res depth
  sm-enc-dim-head: 64
  sm-enc-heads: 8        # high res heads
  sm-enc-mlp-dim: 2048   # high res feedforward dimension

  lg-dim: 49            # low res dimension
  lg-patch-size: 7      # low res patch size
  lg-enc-depth: 3        # low res depth
  lg-enc-dim-head: 64
  lg-enc-heads: 8        # low res heads
  lg-enc-mlp-dim: 2048   # low res feedforward dimensions
  cross-attn-depth: 2    # cross attention rounds
  cross-attn-dim-head: 64
  cross-attn-heads: 8    # cross attention heads
  lg-channels:  80  #196
  sm-channels: 80   #256
  dropout: 0.2
  emb-dropout: 0.2
  